### ISSUE TITLE
Unable to Succesfully Run testing.py

### ISSUE THREAD

**Issue by collapsing-circles** [nkilm/offline-whisperx#4]
Appreciate your script and wrapper.

I cannot seem to get it to run and would very much appreciate any help.

File Name: testing.py

Intended Result: Run transcriber instance

Error Message Output: 
```
Traceback (most recent call last):
  File "c:\Users\...\envs\offline_wx\offline-whisperx\testing.py", line 27, in <module>
    transcriptions = transcriber.transcribe(audio_path=audio_file)
  File "c:\Users\...\envs\offline_wx\offline-whisperx\transcriber.py", line 176, in transcribe
    model = self.load_asr_model()
  File "c:\Users\...\envs\offline_wx\offline-whisperx\transcriber.py", line 137, in load_asr_model
    return load_model(
TypeError: load_model() got an unexpected keyword argument 'vad_model_fp'
```
conda version : 24.7.1
environment python: 3.10

cuda==12.4
whisperx==3.1.1 (In your requirements.txt, I see whisper==3.1.3, could this be an issue?  I don't understand how you have later version)
numpy==1.26.4  
pandas==2.2.2
pytorch==2.4.0     

This setup works with openai/whisper.

I notice that the model paths/files differ slightly to the models provided through your links.  Is this an indication of what my/the issue is?  See below:

```
# testing.py model paths
FASTER_WHISPER_PATH = f"{MODELS_DIR}/faster_whisper_base"
ALIGN_MODEL_DIR = f"{MODELS_DIR}/wav2vec2_base"
VAD_MODEL_FP = f"{MODELS_DIR}/voice_activity_detection/whisperx_vad_segmentation.bin"
```

```
# file/folder names created through links provided in your https://github.com/nkilm/offline-whisperx/tree/main?tab=readme-ov- 
# file#pre-trained-models

./faster-whisper-base/
./wespeaker-voxceleb-resnet34-LM/pytorch_model.bin
./segmentation-3.0/pytorch_model.bin
./wav2vec2_fairseq_base_ls960_asr_ls960.pth
./pytorch_model.bin   (I tried creating a folder and renaming model to match your path: ./voice_activity_detection/whisperx_vad_segmentation.bin)
```
I had a look at https://github.com/m-bain/whisperX/blob/main/whisperx/vad.py, and it points to the same S3 bucket.  
The only file that I see that was adjusted in m-bain/WhisperX repository since you published your script is the alignment.py to subtract out two languages.

Any help would be much appreciated.  And I am new to using Github, but I tried to follow github convention, however, if my question shouldn't be posted here, or does not follow proper protocol/format, please tell me and I will adjust as best I can. 

Thanks again for making the awesome script

**Comment by collapsing-circles** [comment]
I was able to run the script/testing.py using the setup/install method based on dependencies from requirements.txt and by replacing hyphens ("-") with undersocres ("_") in the model names.

**Comment by nkilm** [comment]
Hey @collapsing-circles!

Sorry I couldn't get back to you soon, but I'm glad that you were able to resolve the issue. To answer some of your questions,

> whisperx==3.1.1 (In your requirements.txt, I see whisper==3.1.3, could this be an issue? I don't understand how you have later version)

Yes, the version of `whisperx` does matter, I've written this script for `whisperx==3.1.3` where the import-related issues were fixed.   Before you run the script, please make sure that you have proper version of whisperx. 

> I notice that the model paths/files differ slightly to the models provided through your links. Is this an indication of what my/the issue is? See below:

My guess is that the script was not able to find the VAD model from that path, I've attached a screenshot of model paths in my system where the script works completely file.

![image](https://github.com/user-attachments/assets/7add508a-219e-4542-9c89-70ce6a3e9d01)

---

> Any help would be much appreciated. And I am new to using Github, but I tried to follow github convention, however, if my 
> question shouldn't be posted here, or does not follow proper protocol/format, please tell me and I will adjust as best I can.

> Thanks again for making the awesome script

No issues m8! I'm glad you brought this up and finally it's resolved now! There is no protocol/format I believe(at least for me:)).
